# This file was generated by GoReleaser. DO NOT EDIT.
class Gitwho < Formula
  desc "A simple CLI tool to quickly get information about a GitHub user."
  homepage "https://github.com/tempor1s/gitwho"
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/tempor1s/gitwho/releases/download/v1.0.0/gitwho_1.0.0_macOS-64bit.tar.gz"
    sha256 "2b4a17b634d93ddad4c420a84a0f0484af436f1e10fe24c0c09820edcaaf2906"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/tempor1s/gitwho/releases/download/v1.0.0/gitwho_1.0.0_Linux-64bit.tar.gz"
      sha256 "ea38ec494c7ea83ee8217dd37dabb412662992e74a52ab921e045d8f707122e2"
    end
  end

  def install
    bin.install "gitwho"
  end
end
