# This file was generated by GoReleaser. DO NOT EDIT.
class Gitwho < Formula
  desc "A simple CLI tool to get in depth Github Information about Users and Orgs!"
  homepage "https://github.com/tempor1s/gitwho"
  version "1.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/tempor1s/gitwho/releases/download/v1.1.0/gitwho_1.1.0_macOS-64bit.tar.gz"
    sha256 "19d173c0df36a5eaeed7d0233bae5753af49e705372332cdf3398f3be4061fef"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/tempor1s/gitwho/releases/download/v1.1.0/gitwho_1.1.0_Linux-64bit.tar.gz"
      sha256 "3ca25c92c4082997d345543446c8cd6059ba6d6508073fcb927ae0edc2ae271b"
    end
  end

  def install
    bin.install "gitwho"
  end
end
